### PR TITLE
Added Modali

### PR DESCRIPTION
**Pull request by jcrowson**
Added modali modal-dialog component to the list of overlay components.

### CODE REVIEW

**Comment by z-ax** [comment]
Checked in Safari and there's a noticeable content shift on modal open.

**Comment by bluepeter** [comment]
Hi @jcrowson can you please handle comment from @z-ax before integration?

**Comment by jcrowson** [comment]
@bluepeter @z-ax I've released a new version of Modali: v1.2.0.

It fixes the content shift bug, among other things. Thanks for picking up on this issue, and being so diligent. It goes to show you clearly care about the quality of the libraries in your list. 👍

I'd very much appreciate a re-review. Thanks for the support!

**Comment by bluepeter** [comment]
Nice work!

**Pull request merged**
