### PR TITLE
Add link to redux-easy-boilerplate in "boilerplate" section

### PR DESCRIPTION
**Pull request by anorudes**
Hello, it's a very nice list. Can you add our boilerplate in the list? +)
You can change description if you want

### CODE REVIEW

**Comment by brillout** [comment]
sure+)

Although, is there a reason you didn't use devarchy and did a PR instead?

**Comment by anorudes** [comment]
Devarchy? I have'nt heard of it before. Sorry, i don't know how to make it =)

**Comment by brillout** [comment]
see https://github.com/brillout/awesome-react-components/blob/master/contributing.md

**Comment by anorudes** [comment]
Yee, i read it now, but the boilerplate hasn't a npm package. Do you can't add it without a npm package?
Then you can just close PR =)

**Comment by brillout** [comment]
unfortunately npm is required

**Comment by 1544592680** [comment]
China

**Pull request closed without merging**
