### PR TITLE
add shameless plug of Wildcard API + change maintainer text

### PR DESCRIPTION
**Pull request by brillout**
@bluepeter What do you think? Please reject the PR if you disagree with anything. I guess that your shameless plug is important to you and I definitely want to preserve your conversation rate. Let me know what you think.

### CODE REVIEW

**Comment by brillout** [comment]
Btw. I love your Fluxguard icon &mdash; you should add it to the description:) But as you wish obviously:)

**Comment by brillout** [comment]
Actually I'm wondering: what company designed your logo? I'd be up to pay some money to have a better Wildcard logo:)

**Comment by bluepeter** [comment]
LGTM! Thanks for the logo compliments! I got it via a competition on 99designs with the winning designer being... https://99designs.com/social-media-pack/contests/material-design-inspired-logo-software-service-enterprise-security-788479/entries (it looks like they deleted their account for some reason! But I reco 99designs as a good resources for logo competitions.)

**Comment by brillout** [comment]
Good to know, thanks.

I've updated the maintainer text again: https://github.com/brillout/awesome-react-components/commit/6a2f14ec9acb1c45bc0d897e819d6ecd8a46ff00.

Please overwrite my changes if you feel like it.

**Comment by bluepeter** [comment]
LGTM! 😆

**Pull request merged**
