### PR TITLE
update readme.md / added Bit

### PR DESCRIPTION
**Pull request by jonisar**
Added Bit under Misc for isolating, sharing, organizing and syncing React components between React projects and apps.

* Don't create a pull request to add a library, instead use [devarchy.com/react](https://devarchy.com/react).
* Only create a pull request to change the categorization.
* Open an issue if you are not sure how to change the categorization to fit a library you want to add.

### CODE REVIEW

**Comment by brillout** [comment]
Is there a reason you didn't use devarchy?

**Comment by jonisar** [comment]
My bad, sorry.
Should I add there or just keep the pr and use devarchy next time?

**Comment by brillout** [comment]
Devarchy helps me manage new library additions. Closing the PR and using devarchy instead would help me. Thanks!

**Comment by jonisar** [comment]
K I did. thanks

**Pull request closed without merging**
