### PR TITLE
Add react-color to colorpickers list

### PR DESCRIPTION
**Pull request by pdillon**

### CODE REVIEW

**Comment by brillout** [comment]
thanks!

> To add a component / library, add an entry at devarchy.com/react-components. 
It will be added to the catalog once enough users have approved it.

I'm curious: is there a reason why you didn't use http://devarchy.com/react-components?

**Comment by pdillon** [comment]
Hi, pretty sure I made the PR before the readme was updated.

**Comment by brillout** [comment]
Ah ok, sorry about the question then

**Comment by brillout** [comment]
No need to submit, I just merged it

**Pull request merged**
