### PR TITLE
Added 'react-sticky-node' component to 'Sticky' section.

### PR DESCRIPTION
**Pull request by visortelle**
I'm sorry, but http://devarchy.com/react-components return me `{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}` when I try login.

### CODE REVIEW

**Comment by brillout** [comment]
Thanks for letting me know, login should work again now. (Neat component btw.)

**Comment by visortelle** [comment]
Done.

**Comment by brillout** [comment]
Upvoted:) I guess we can close this PR

**Comment by visortelle** [comment]
Thanks.

**Pull request closed without merging**
