### PR TITLE
Add react-monacoeditor

### PR DESCRIPTION
**Pull request by jaywcjlove**

### CODE REVIEW

**Comment by bluepeter** [comment]
Thanks. In future, please remember to remove one item from the list for each item you add.

**Comment by jaywcjlove** [comment]
Why delete an item？ @bluepeter

**Comment by bluepeter** [comment]
This is how we keep the list fresh and up-to-date. We made a rule that every new addition must remove an outdated, old, stale, uncool item, too.

**Comment by jaywcjlove** [comment]
@bluepeter 👌

**Pull request merged**
