### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by r3nya**
Added another starter kit. :wink:

### CODE REVIEW

**Comment by brillout** [comment]
thanks for the PR!

> another

Precisely, there are a lot of them. Too much of them?
So what does your starter kit better than the other ones?

>To add a component / library, add an entry at devarchy.com/react-components. 
It will be added to the catalog once enough users have approved it.

Is there a reason why you didn't use http://devarchy.com/react-components?

**Comment by r3nya** [comment]
Hey @brillout !

To be honest I didn't know about http://devarchy.com/react-components :)

I will add our starter-kit into this catalog. Thanks!

Btw, will you add my PR?

**Comment by brillout** [comment]
> Btw, will you add my PR?

-> 

> Precisely, there are a lot of them. Too much of them?
So what does your starter kit better than the other ones?

So if you make convincing arguments and add them to the readme, then sure:)

**Comment by r3nya** [comment]
Ah ... understood.

@brillout usually all boilerpaltes has React+Redux w/o server side rendering.
Our boilerplate/starter-kit has React server side rendering with GraphQL integration.
And we use Webpack fro build all JS files (backend and frontend). Also, we use CSS Modules too. 

It's really very powerfull starter-kit.

**Comment by brillout** [comment]
ok 👍 
closing this in favor of devarchy, just add it there (i'll personally approve it if nobody does)

**Pull request closed without merging**
