### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by jerryshew**
Searching for [react-uikits](https://github.com/jerryshew/react-uikits) from [devarchy.com/react](https://devarchy.com/react) , not found.

### CODE REVIEW

**Comment by brillout** [comment]
Thanks for the PR! Any reasons you did a PR instead of using Devarchy?

**Comment by jerryshew** [comment]
@brillout Using Devarchy not found react-uikits, so create this PR

**Comment by jerryshew** [comment]
@brillout Can you add [https://github.com/jerryshew/react-uikits](https://github.com/jerryshew/react-uikits) to this list?

**Comment by abenhamdine** [comment]
@jerryshew you'd rather add react-uikits directly on https://devarchy.com/react

**Comment by jerryshew** [comment]
@abenhamdine thanks

**Pull request closed without merging**
