### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by scniro**
adding https://github.com/scniro/react-codemirror2

* Don't create a pull request to add a library, instead use [devarchy.com/react](https://devarchy.com/react).
* Only create a pull request to change the categorization.
* Open an issue if you are not sure how to change the categorization to fit a library you want to add.

### CODE REVIEW

**Comment by brillout** [comment]
Any reason you didn't use devarchy?

**Comment by brillout** [comment]
Closing for now.

**Comment by scniro** [comment]
@brillout I did actually submit it about 2 months ago and just, well nothing happened. It never showed up.

**Comment by brillout** [comment]
Are you sure you added it on devarchy? Can't find it; https://devarchy.com/react/react-codemirror2

**Comment by brillout** [comment]
Can find Jed's one https://devarchy.com/react/codemir but not yours

**Comment by scniro** [comment]
hm weird, I swore I did this before but I just tried adding it now and all appears to be okay. It now appears to be in some sort of status

> Awaiting upvotes

I should be good now?

**Comment by brillout** [comment]
> I should be good now?
Yes, it will be added here once approved.

> hm weird

I just looked it up and what happened is that you added the library to devarchy but didn't add it to the "Need". The addition form can be bit confusing as it is a two-way process. I'll see if I can improve it.

**Comment by scniro** [comment]
@brillout Great! thanks for your assistance. I'll keep an eye out for it to become live.

**Pull request closed without merging**
