### PR TITLE
Add react-emoji-react

### PR DESCRIPTION
**Pull request by Kikobeats**
Not sure if is the best section for that but it's totally worth it

### CODE REVIEW

**Comment by brillout** [comment]
Hi, thanks for the PRs! Is there a reason you didn't use devarchy to add the libraries? It's then easier for to manage addition requests

**Comment by Kikobeats** [comment]
what is devarchy?

**Comment by brillout** [comment]
https://devarchy.com/react-components

Would be awesome if you could add them there. Requests are easier to manage on devarchy.

**Comment by brillout** [comment]
It is included in the catalog. Thanks for the PR! Let me know if there is a reason you didn't use devarchy to add it.

**Pull request closed without merging**
