### PR TITLE
Added simple-redux-form

### PR DESCRIPTION
**Pull request by mihirsoni**
Added simple redux form

### CODE REVIEW

**Comment by brillout** [comment]
thanks for the PR.

> To add a component / library, add an entry at devarchy.com/react-components. 
It will be added to the catalog once enough users have approved it.
is there a reason why you didn't use http://devarchy.com/react-components?

About `simple-redux-form`:
 - the text is difficult to read because of many english mistakes
 - From reading the text, I don't get why I should use `simple-redux-form` over `redux-form`

**Comment by mihirsoni** [comment]
@brillout Thanks for reviewing it, I have modified it. please let me know your views.

**Comment by brillout** [comment]
> For small forms I still wanted to use the same way , but redux-form was heavey for small / few forms

I would elaborate that point


> the text is difficult to read because of many english mistakes

I was referring to the readme

**Comment by mihirsoni** [comment]
@brillout  I have updated readme today , if you could consider. 
Thanks a lot.

**Pull request closed without merging**
