### PR TITLE
Remove Bootstrap - no longer awesome.

### PR DESCRIPTION
**Pull request by bluepeter**

### CODE REVIEW

**Comment by ericblade** [comment]
ok, i'm curious, why?

**Comment by bluepeter** [comment]
It's over-used to the point that its design patterns have become fairly generic; at the same time, it's becoming increasingly irrelevant (e.g., https://trends.google.com/trends/explore?date=today%205-y&geo=US&q=bootstrap) with better options out there. Moreover, since it's such a well-known project, I don't see its inclusion on this list as adding anything in terms of something unique, compelling, or magical. Just my opinion, of course. I personally still use Bootstrap all the time... but like jQuery, it feels as though its day in the sun has passed.

**Comment by bluepeter** [comment]
Incidentally, if you feel otherwise, feel free to PR to re-include it!

**Comment by ericblade** [comment]
I have no opinion, was just curious what would cause something popular to no longer be awesome. :-)

**Pull request merged**
